### PR TITLE
Allow ip:port syntax in IP header

### PR DESCRIPTION
**Pull request by stevenvergenz**
This PR will successfully parse both IP and port from a header like `X-Forwarded-For: 1.2.3.4:8080, 2.3.4.5:9000`. This is necessary when using an Azure App Gateway, as they add ports, and you can't remove them without a very complicated rewrite rule.

### CODE REVIEW

**Comment by lpinca** [comment]
Can you please remove package-lock.json?

**Comment by stevenvergenz** [comment]
@lpinca Sure. Is a package-lock not desirable?

**Comment by lpinca** [comment]
I don't think it adds much value here. There are only dev dependencies.

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
